# Generated by Django 2.2.7 on 2020-01-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='customerid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
